apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver
spec:
  selector:
    matchLabels:
      app: driver

  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:
        - name: driver
          image: img-deployment
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: driver

---
  
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: driver-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:  
    - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: driver-vs
spec:
  hosts:
  - "*"
  gateways:
  - driver-gateway
  http:
  - match:
    - uri:
        prefix: /drivers
    route:
    - destination:
        port:
          number: 8081
        host: driver-service