steps:
    # - name: node
    #   entrypoint: npm
    #   args: ['install']
  
    # - name: node
    #   entrypoint: npm
    #   args: ['run', 'build'] 
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-f','Dockerfile.prod','--tag=gcr.io/$PROJECT_ID/maratona-order:$SHORT_SHA', '.']
  
    - id: "Pushing  Image"
      name: 'gcr.io/cloud-builders/docker'
      args: ['push','gcr.io/$PROJECT_ID/maratona-order:$SHORT_SHA']
  
    - id: Ajust deployment for kubectl
      name: 'gcr.io/cloud-builders/gcloud'  
      entrypoint: '/bin/sh'  
      args:
        - '-c'
        - |
          sed 's#img-deployment#gcr.io/$PROJECT_ID/maratona-order:$SHORT_SHA#g' ./k8s/order.yaml > k8s/order-new.yaml; 
          cat k8s/order-new.yaml;
  
    - id: "Deploying to kubernetes"
      name: 'gcr.io/cloud-builders/kubectl'
      args: 
      - 'apply'
      - '-f'
      - 'k8s/order-new.yaml'
      env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=maratona-istio'
    
images: ['gcr.io/$PROJECT_ID/maratona-order']