apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver
spec:
  selector:
    matchLabels:
      app: driver

  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:
        - name: driver
          image: wesleywillians/maratona-driver
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: driver-service
  labels:
    app: driver-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
  selector:
    app: driver