apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-spa
spec:
  selector:
    matchLabels:
      app: map-spa

  template:
    metadata:
      labels:
        app: map-spa
    spec:
      containers:
        - name: map-spa
          image: wesleywillians/maratona-map-spa
          ports:
            - containerPort: 80
          
---

apiVersion: v1
kind: Service
metadata:
  name: map-spa-service
  labels:
    app: map-spa-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: map-spa
